### PR TITLE
Update datetimeindex handling

### LINKED ISSUE #31: Error with datetime while running tests
I'm getting this error while running the tests (docstring of tz_localize elided for brevity)

```
partd/tests/test_pandas.py:110: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
partd/pandas.py:175: in deserialize
    for (h, b) in zip(headers[2:], bytes[2:])]
partd/pandas.py:175: in <listcomp>
    for (h, b) in zip(headers[2:], bytes[2:])]
partd/pandas.py:143: in block_from_header_bytes
    values = pd.DatetimeIndex(values).tz_localize('utc').tz_convert(
/usr/lib/python3.7/site-packages/pandas/core/accessor.py:91: in f
    return self._delegate_method(name, *args, **kwargs)
/usr/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py:721: in _delegate_method
    result = operator.methodcaller(name, *args, **kwargs)(self._data)

E               TypeError: Already tz-aware, use tz_convert to convert.

/usr/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py:1049: TypeError
```
This is with pandas 0.24.1.
Tests run fine if I replace line 143 in pandas.py with just `values = pd.DatetimeIndex(values)`, it seems like pandas restores the timezone just fine, not sure which version it started to work.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #31

### CODE REVIEW

**Comment by TomAugspurger** [comment]
This fix isn't quite right. The issue is actually on the serialization side.

When serializing, we access Block.values. For a DatetimeTZBlock this was previously an m8[ns] ndarray. Now it's a DatetimeArray.

`np.asarray(DatetimeArray)` returns an object-dtype ndarray of Timestamps (which retain the tz info). Previously this was a an m8[ns] ndarray localized to UTC.

I think the best option is to serialize as integer values.

**Comment by TomAugspurger** [comment]
@mrocklin merging this later today if no objections.

This probably merits a partd release. I'm happy to help with that, but would need to be added to the maintainers on PyPI (account name is `tomaugspurger`).

**Comment by mrocklin** [comment]
Done!

**Comment by TomAugspurger** [comment]
Thanks. I'll do a partd release later today.

**Comment by TomAugspurger** [comment]
Pushed 0.3.10 to PyPI.

**Pull request merged**
